### PR TITLE
RSS Feed

### PR DESCRIPTION
**Pull request by faiyazs**

### CODE REVIEW

**Comment by gcallah** [comment]
I don't understand the commit message "Add files via upload."

**Comment by faiyazs** [comment]
Sorry , forgot to add comment, it was "Minor bug issue fixed"

**Comment by akshaytambe** [comment]
@gcallah, It look's locally. Should we merge and deploy to Prod?

**Comment by gcallah** [comment]
Faiyazs, that is still inadequate: please say what bug you fixed!

**Comment by faiyazs** [comment]
"Removed the extra '}' present at the end of the code in last <script> tag in devops/templates/base.html file which prevented the AJAX call from extracting the data"

**Pull request merged**
