### PR TITLE
Displays correct navigation link after graded quiz

### PR DESCRIPTION
**Pull request by mkong0216**
If user passed quiz, displays link to next module. If user fails quiz, displays link to previous module.

### CODE REVIEW

**Comment by akshaytambe** [comment]
Have you tested this on our latest docker container?
If not, try:
make container
./devops_container.sh
./local.sh

**Comment by mkong0216** [comment]
@akshaytambe I tested it locally if that's what you mean? When I try doing the ./devops_container.sh after running make container, I get the following error: `docker: invalid reference format: repository name must be lowercase.`

**Comment by akshaytambe** [comment]
Also, I like the way you are naming the branches associated with tickets (Much better way in industry standards)!

**Comment by akshaytambe** [comment]
Okay let me check the docker part

**Pull request merged**
